# Generated by Django 2.2.5 on 2019-09-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='some text', max_length=50)),
                ('jobtitle', models.CharField(max_length=50)),
                ('jobdescription', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='some text', max_length=50)),
                ('jobcategory', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pay_grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paygrade', models.CharField(default='some text', max_length=50)),
                ('currency', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='some text', max_length=50)),
                ('component_name', models.CharField(max_length=50)),
                ('types', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Work_shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='some text', max_length=50)),
                ('workshift', models.CharField(max_length=50)),
                ('fro', models.IntegerField()),
                ('to', models.IntegerField()),
            ],
        ),
    ]
