# Generated by Django 2.2.5 on 2019-09-21 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employment_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='some text', max_length=50)),
                ('employment_status', models.CharField(default='some text', max_length=50)),
            ],
        ),
    ]
