# Generated by Django 2.2.5 on 2019-09-24 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_date', models.DateField()),
                ('date_of_permanency', models.DateField()),
                ('job_title', models.IntegerField(default=1)),
                ('employement_status', models.IntegerField(default=1)),
                ('job_category', models.IntegerField(default=1)),
                ('work_shifts', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Personal_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, null=True)),
                ('middle_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('employee_id', models.IntegerField()),
                ('date_of_birth', models.DateTimeField()),
                ('marital_status', models.SmallIntegerField(default=1)),
                ('gender', models.SmallIntegerField(default=1)),
                ('nationality', models.SmallIntegerField(default=1)),
                ('nick_name', models.CharField(blank=True, max_length=150)),
                ('aadhar_card_no', models.BigIntegerField()),
            ],
        ),
    ]
