# Generated by Django 2.2.5 on 2019-09-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('per_info_mng', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_details',
            name='employement_status',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='employee_details',
            name='job_category',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='employee_details',
            name='job_title',
            field=models.BigIntegerField(default=1),
        ),
    ]
