# Generated by Django 2.2.5 on 2019-09-25 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('per_info_mng', '0002_auto_20190924_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=150, null=True)),
                ('job_title', models.BigIntegerField(default=1)),
                ('employement_status', models.BigIntegerField(default=1)),
                ('nationality', models.SmallIntegerField(default=1)),
            ],
        ),
    ]
